version: '3.8'
services:
  php-apache:
    container_name: php-apache
    build:
      context: ./server
    network_mode: "host"
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0.32-1.2.11-server
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: abcd
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_HOST: '%'
